# INSERT INTO PLAYER (EMAIL, PASSWORD, NICKNAME, CREATED_DATE, UPDATED_DATE) VALUES ('test1@test.com', 'password', 'test1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
# INSERT INTO PLAYER (EMAIL, PASSWORD, NICKNAME, CREATED_DATE, UPDATED_DATE) VALUES ('test2@test.com', 'password', 'test2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
# INSERT INTO PLAYER (EMAIL, PASSWORD, NICKNAME, CREATED_DATE, UPDATED_DATE) VALUES ('test3@test.com', 'password', 'test3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
